AWSTemplateFormatVersion: 2010-09-09
Description: Academy Demo CloudFormation

Resources:
  MyQueue:
    Type: 'AWS::SQS::Queue'
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead